using EGovernance;
using Banking;
CentralGov bjpGovt=new CentralGov();
TaxOperation itOperation=new TaxOperation(bjpGovt.DeductIncomeTax);
TaxOperation proOperation=new TaxOperation(bjpGovt.DeductProfessionalTax);
Account  acct123=new Account(6000);
acct123.overBalance+=itOperation;
acct123.overBalance+=proOperation;
Console.WriteLine("Enter Amount to be deposited");
double amount=double.Parse(Console.ReadLine());
acct123.Deposit(amount);
Console.WriteLine("Before Tax processing");
Console.WriteLine(acct123);
acct123.ProcessTax();
Console.WriteLine("After Tax processing");
Console.WriteLine(acct123);
