using Mathematics;
using tflDrawing;
Console.WriteLine("Hello, World!");
int i = 45;
Complex complex = new Complex(1, 2); 
Complex complex2 = new Complex(1, 87);
int resultreal = complex.Real;
int resultimag = complex2.Imag;
Shape theShape = new Line();
theShape.Draw();
Shape theShape2 = new Circle();
theShape2.Draw();
