// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class GoogledotnetTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void googledotnet() {
    // Test name: googledotnet
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.google.com/");
    // 2 | setWindowSize | 542x728 | 
    driver.Manage().Window.Size = new System.Drawing.Size(542, 728);
    // 3 | mouseOver | css=.gb_n | 
    {
      var element = driver.FindElement(By.CssSelector(".gb_n"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 4 | mouseOut | css=.gb_n | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 5 | click | id=APjFqb | 
    driver.FindElement(By.Id("APjFqb")).Click();
    // 6 | type | id=APjFqb | dotnet
    driver.FindElement(By.Id("APjFqb")).SendKeys("dotnet");
    // 7 | click | css=.eKjLze .LC20lb | 
    driver.FindElement(By.CssSelector(".eKjLze .LC20lb")).Click();
    // 8 | runScript | window.scrollTo(0,106) | 
    js.ExecuteScript("window.scrollTo(0,106)");
    // 9 | click | linkText=Get started | 
    driver.FindElement(By.LinkText("Get started")).Click();
    // 10 | click | css=#microservices > .media-heading | 
    driver.FindElement(By.CssSelector("#microservices > .media-heading")).Click();
    // 11 | click | linkText=Install Docker | 
    driver.FindElement(By.LinkText("Install Docker")).Click();
    // 12 | click | linkText=Continue | 
    driver.FindElement(By.LinkText("Continue")).Click();
    // 13 | click | linkText=Continue | 
    driver.FindElement(By.LinkText("Continue")).Click();
    // 14 | click | linkText=Next steps | 
    driver.FindElement(By.LinkText("Next steps")).Click();
  }
}
